### ISSUE TITLE
# [Codecov](https://app.codecov.io/gh/codecov/cpp-11-standard/compare/9?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=codecov) Report

### ISSUE THREAD

**Issue by ghost** [codecov/cpp-11-standard#10]
# [Codecov](https://app.codecov.io/gh/codecov/cpp-11-standard/compare/9?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=codecov) Report
> Merging [#9](https://app.codecov.io/gh/codecov/cpp-11-standard/compare/9?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=codecov) (13895ff) into [master](https://codecov.io/gh/codecov/cpp-11-standard/commit/1742e25b41fd2f6864d468597d39609f2b8b715c?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=codecov) (1742e25) will **not change** coverage.
> The diff coverage is `n/a`.

```diff
@@           Coverage Diff           @@
##           master       #9   +/-   ##
=======================================
  Coverage   62.50%   62.50%           
=======================================
  Files           1        1           
  Lines           8        8           
=======================================
  Hits            5        5           
  Misses          3        3           
```

Help us with your feedback. Take ten seconds to tell us [how you rate us](https://about.codecov.io/nps?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=codecov). Have a feature suggestion? [Share it here.](https://app.codecov.io/gh/feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=codecov)

_Originally posted by @codecov[bot] in https://github.com/codecov/cpp-11-standard/issues/9#issuecomment-1297646925_

**Comment by Red3amer** [comment]
Hilp i no dont speck englsh
